# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20180119_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operarecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 10, 19, 33, 320305), max_length=255, verbose_name='\u65f6\u95f4'),
        ),
    ]
