# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20180124_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operarecord',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255, verbose_name='\u65f6\u95f4'),
        ),
    ]
