# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180115_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppprojectdetail',
            name='deploy_success',
            field=models.IntegerField(default=0, verbose_name='\u90e8\u7f72\u6210\u529f\u4e0e\u5426'),
        ),
        migrations.AlterField(
            model_name='ppstate',
            name='code',
            field=models.IntegerField(),
        ),
    ]
