# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP\u5730\u5740'),
        ),
    ]
